### ISSUE TITLE
The `forwarder` package is not pip installable

### ISSUE THREAD

**Issue by g5t** [ess-dmsc/forwarder#249]
The presence of a `pyproject.toml` file would appear to indicated that a Python module could be installed from this repository, either

```bash
git clone https://github.com/ess-dmsc/forwarder.git
python -m pip install ./forwarder
```
or
```bash
python -m pip install git+https://github.com/ess-dmsc/forwarder.git
```
but either method fails due to misconfiguration of the project for `setuptools`.

Is it envisioned that this project should not be installable? Or can the `pyproject.toml` be updated to produce an installable project?

**Comment by mattclarke** [comment]
It isn't meant to be pip installable - it is meant to be cloned.
The pyproject.toml is used to avoid having separate .ini files for black, isort, flake8, mypy, etc.

**Comment by mattclarke** [comment]
We can make it installable if needs be though.

**Comment by g5t** [comment]
Thanks for merging #251 🥳 
Installing via `python -m pip install git+https://github.com/ess-dmsc/forwarder.git` now works as I in intially expected
