### ISSUE TITLE
Add instructions for configuring a running instance

### ISSUE THREAD

**Issue by mattclarke** [ess-dmsc/forwarder#27]
It isn't obvious that you **need** to set the --output-broker so that should be made clear.

The rest of the details can be copied from the C++ version.

**Comment by matthew-d-jones** [comment]
I made it not required and defaulted to `localhost:9092` so that the C++ codebase system tests could be run without any changes. Now that we have been making changes to the system tests we can remove the default, make it required and update the system test run configs as necessary.
