### ISSUE TITLE
Alarm status incorrect when using PVA

### ISSUE THREAD

**Issue by mattclarke** [ess-dmsc/forwarder#4]
Something seems to be wrong with handling of p4p alarms. I don't think the issue is just mapping from EPICS alarm enum to our flatbuffer enum. In the system test if I print the raw value of the alarm status from p4p it doesn't change when expected:
```
ERROR:python-forwarder:new status: 3, cached_status: NONE or DIFF, value 0.0
ERROR:python-forwarder:new status: 3, cached_status: 3, value 17.0
ERROR:python-forwarder:new status: 3, cached_status: 3, value 18.0
```
Experiment with manually changing the SoftIOC PV value with `ctxt.put('pv:name', 5)` and check alarm status from  `V = ctxt.get('pv:name')`.

**Comment by matthew-d-jones** [comment]
The alarm status enum in PVA is:
NONE,DEVICE,DRIVER,RECORD,DB,CONF,UNDEFINED,CLIENT
(http://epics-pvdata.sourceforge.net/informative/developerGuide/developerGuide.html#alarm)
so we are getting NONE or RECORD, we need to get the RECORD alarm statuses somehow.
