### ISSUE TITLE
Catch full producer buffer exception

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/forwarder#60]
A `try-except` should be used to catch `BufferError` exception which may be raised in `produce()`. This occurs when the producer buffer is full: sending messages to the broker is not keeping up with calls to `produce()`.

**Comment by kmurica** [comment]
@matthew-d-jones : could you clarify a bit on what behavior is anticipated when the exception gets caught? Thanks!

**Comment by kmurica** [comment]
Answer: Error message with a clear indication that data is lost.

**Comment by kmurica** [comment]
Closing issue as PR has been merged into main.
